version: 2

builds:
  - binary: spark-cli
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/Spark-Rewards/homebrew-spk/cmd.Version={{.Version}}
      - -X github.com/Spark-Rewards/homebrew-spk/cmd.Commit={{.Commit}}
      - -X github.com/Spark-Rewards/homebrew-spk/cmd.Date={{.Date}}

archives:
  - formats: ['tar.gz']
    name_template: "spark-cli_{{ .Os }}_{{ .Arch }}"

brews:
  - name: spark-cli
    repository:
      owner: Spark-Rewards
      name: homebrew-spk
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/Spark-Rewards/homebrew-spk"
    description: "Workspace CLI for multi-repo development"
    license: "MIT"
    install: |
      bin.install "spark-cli"
    test: |
      system "#{bin}/spark-cli", "version"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
