# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewSpk < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spk"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.1/spk_darwin_amd64.tar.gz"
      sha256 "d5739deec58769c80b9eb7a3614589ac99478c3d7f54d62614127b4ef71ff4b0"

      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.1/spk_darwin_arm64.tar.gz"
      sha256 "4a48f0fe5fa42874d433ce3d9790278ab1d28cbba92d5c5e702ad92e5c5c7ecd"

      def install
        bin.install "spk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.1/spk_linux_amd64.tar.gz"
      sha256 "10dcf681d952995b9f9926b4b913be6ff54bf928451f2452f1463eaa6e341be9"
      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.1/spk_linux_arm64.tar.gz"
      sha256 "dbec8a923ef533e386a4453d7e75e66c656f248bac94b2c7985addd940f79f8d"
      def install
        bin.install "spk"
      end
    end
  end

  test do
    system "#{bin}/spk", "version"
  end
end
