# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SparkCli < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spk"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.2.0/spark-cli_darwin_amd64.tar.gz"
      sha256 "8e706b6e5e9d8a219ea8d2a9740d68fc48ebcf0124f1ada2aa7ef41f691cb44d"

      def install
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.2.0/spark-cli_darwin_arm64.tar.gz"
      sha256 "fc73d3fb51e794271842af029eed8bfe15dba87023078e7930329b0ab9fd44cb"

      def install
        bin.install "spark-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.2.0/spark-cli_linux_amd64.tar.gz"
      sha256 "712d170fe5cdd8af8d31f6f1ae0dd77b53f4bb42516663ce8c103c454b0e384c"
      def install
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.2.0/spark-cli_linux_arm64.tar.gz"
      sha256 "b0e84adca6df06a6559dd890c6dbd84499785bf48cab93e178b601e736950bcd"
      def install
        bin.install "spark-cli"
      end
    end
  end

  test do
    system "#{bin}/spark-cli", "version"
  end
end
