# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SparkCli < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spark-cli"
  version "0.2.26"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.26/spark-cli_darwin_amd64.tar.gz"
      sha256 "4c19c92f1fd11d19f7846b5be75c6724ee510cca3dddc15e927b9a102457156e"

      define_method(:install) do
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.26/spark-cli_darwin_arm64.tar.gz"
      sha256 "9e5c9de41f58ca10f7f31ff5c3e9507460197de2305a49492292c6a5d90d9082"

      define_method(:install) do
        bin.install "spark-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.26/spark-cli_linux_amd64.tar.gz"
      sha256 "d6a79cde3b46ba0d8421f5990fec1314fd512a36b078a28536e78b2ccf70fc5c"
      define_method(:install) do
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.26/spark-cli_linux_arm64.tar.gz"
      sha256 "d6bbde1fe9eaaf917c3deb08ce708d20a8ed4c1f8d37835a6173475c20247220"
      define_method(:install) do
        bin.install "spark-cli"
      end
    end
  end

  test do
    system "#{bin}/spark-cli", "version"
  end
end
