# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spk < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spk"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.11/spk_darwin_amd64.tar.gz"
      sha256 "51ccb33eaee7ddd8207d316568a5c4efa465c3f2657245a60fbb102087ba099d"

      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.11/spk_darwin_arm64.tar.gz"
      sha256 "6d59b8f8dce89725c08babe5b9e62f7d8716afaa8b8e5355819de66ec2ffb42b"

      def install
        bin.install "spk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.11/spk_linux_amd64.tar.gz"
      sha256 "46ab0da4e941c5be483ad376103d6d11d618cbd669bdfdca0379c27e7f626d7a"
      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.11/spk_linux_arm64.tar.gz"
      sha256 "09a4e4fdc6cc50208699b806064ce8fa71bfd5d718b8b3d1f8f6dbd2660295c9"
      def install
        bin.install "spk"
      end
    end
  end

  test do
    system "#{bin}/spk", "version"
  end
end
