# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spk < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spk"
  version "0.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.13/spk_darwin_amd64.tar.gz"
      sha256 "6477337b92bdd0bf0f32af30cb18901379317715a1bfb4264eec649f201e933f"

      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.13/spk_darwin_arm64.tar.gz"
      sha256 "c174d7e60b8bee789e47ee07e7e0db8b30de586f2717b6d220636139a839d31d"

      def install
        bin.install "spk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.13/spk_linux_amd64.tar.gz"
      sha256 "4196698047242599af041702e03ee369a508675733a2a446d3bd0f08203a4f7a"
      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.13/spk_linux_arm64.tar.gz"
      sha256 "39ae1df9667865ed1f9eeda142889fcb935acb5a05a2068a0e3275cfe4b89329"
      def install
        bin.install "spk"
      end
    end
  end

  test do
    system "#{bin}/spk", "version"
  end
end
