# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spk < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spk"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.2/spk_darwin_amd64.tar.gz"
      sha256 "72f03bd81633155d4040d7b0bd0b3a48ce444bfa96e731c91cc183a32acbc4e6"

      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.2/spk_darwin_arm64.tar.gz"
      sha256 "db4d4bd1ff9d8c33b063a50f23cd8d78a2a790692ec8e9dc0a9624e7da40fd76"

      def install
        bin.install "spk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.2/spk_linux_amd64.tar.gz"
      sha256 "8fee38f6c18b01504ec888aabfcd2d2ad274d9b2009f00bdd694683e63df9c24"
      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.2/spk_linux_arm64.tar.gz"
      sha256 "0140eaef6dffbdbb94332baf7168908abe6e0588c01e149433171ff2c6cb537f"
      def install
        bin.install "spk"
      end
    end
  end

  test do
    system "#{bin}/spk", "version"
  end
end
